version: "3"

services:
    app:
        build:
            context: ./docker/dev/app
            args:
                - APP_IMAGE_VERSION=${APP_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /var/www/html
        depends_on:
            - php
            - nginx
            - database
            - mailer
        volumes:
            - .:/var/www/html/:ro
            - ./data:/var/www/html/data/:rw
            - ./var:/var/www/html/var/:rw
        networks:
            - backend

    php:
        build:
            context: ./docker/dev/php
            args:
                - PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${PHP_PORT}:9000
        volumes:
            - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - backend

    nginx:
        build:
            context: ./docker/dev/nginx
            args:
                - NGINX_IMAGE_VERSION=${NGINX_IMAGE_VERSION}
                - PHP_UPSTREAM_CONTAINER=php
                - PHP_UPSTREAM_PORT=${PHP_PORT}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${NGINX_HTTP_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        depends_on:
            - php
        volumes:
            - .:/var/www/html/:ro
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/dev/nginx/sites-available/:/etc/nginx/sites-available:ro
            - ./docker/dev/nginx/ssl/:/etc/nginx/ssl:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - backend

    database:
        build:
            context: ./docker/dev/database
            args:
                - DATABASE_IMAGE_VERSION=${DATABASE_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /var/www/html
        environment:
            - POSTGRES_DB=${DATABASE_DB}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_USER=${DATABASE_USER}
        ports:
            - ${DATABASE_PORT}:5432
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        networks:
            - backend

    mailer:
        build:
            context: ./docker/dev/mailer
            args:
                - MAILER_IMAGE_VERSION=${MAILER_IMAGE_VERSION}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${MAILER_PORT_1}:1025
            - ${MAILER_PORT_2}:1080
        networks:
            - backend

volumes:
    database_data:

networks:
    backend:
