version: "3"

services:
    php:
        build:
            context: ./docker/build/php
            args:
                - PHP_VERSION=${PHP_VERSION:-fpm-alpine}
        image: ghcr.io/rbrauner/learning-symfony-guestbook-php:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        depends_on:
            - database
            - mailer

    nginx:
        build:
            context: ./docker/build/nginx
            args:
                - NGINX_VERSION=${NGINX_VERSION:-alpine}
                - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER:-php}
                - PHP_UPSTREAM_PORT=${PHP_PORT:-9000}
        image: ghcr.io/rbrauner/learning-symfony-guestbook-nginx:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        depends_on:
            - php

    database:
        build:
            context: ./docker/build/database
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION:-15-alpine}
        image: ghcr.io/rbrauner/learning-symfony-guestbook-database:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        environment:
            - POSTGRES_DB=${POSTGRES_DB:-app}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
            - POSTGRES_USER=${POSTGRES_USER:-app}

    mailer:
        build:
            context: ./docker/build/mailer
            args:
                - MAILER_VERSION=${MAILER_VERSION:-latest}
        image: ghcr.io/rbrauner/learning-symfony-guestbook-mailer:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
