version: "3"

services:
    php:
        build:
            context: ./docker/dev/php
            args:
                - PHP_VERSION=${PHP_VERSION:-fpm-alpine}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${PHP_PORT:-9000}:9000
        depends_on:
            - database
            - mailer
        volumes:
            - .:/var/www/html/:ro
            - ./data:/var/www/html/data/:rw
            - ./var:/var/www/html/var/:rw
            - ./docker/dev/php/php.ini:/usr/local/etc/php/php.ini:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - backend

    nginx:
        build:
            context: ./docker/dev/nginx
            args:
                - NGINX_VERSION=${NGINX_VERSION:-alpine}
                - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER:-php}
                - PHP_UPSTREAM_PORT=${PHP_PORT:-9000}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${NGINX_PORT_HTTP:-80}:80
            - ${NGINX_PORT_HTTPS:-443}:443
        depends_on:
            - php
        volumes:
            - .:/var/www/html/:ro
            - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/dev/nginx/sites-available/:/etc/nginx/sites-available:ro
            - ./docker/dev/nginx/ssl/:/etc/nginx/ssl:rw
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        networks:
            - backend

    database:
        build:
            context: ./docker/dev/database
            args:
                - POSTGRES_VERSION=${POSTGRES_VERSION:-15-alpine}
        platform: linux/x86_64
        working_dir: /var/www/html
        environment:
            - POSTGRES_DB=${POSTGRES_DB:-app}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
            - POSTGRES_USER=${POSTGRES_USER:-app}
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        networks:
            - backend

    mailer:
        build:
            context: ./docker/dev/mailer
            args:
                - MAILER_VERSION=${MAILER_VERSION:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - 1025
            - 1080
        networks:
            - backend

volumes:
    database_data:

networks:
    backend:
