version: "3"

services:
    php:
        image: ghcr.io/rbrauner/learning-symfony-guestbook-php:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${PHP_PORT:-9000}:9000
        depends_on:
            - database
            - mailer
        volumes:
            - app_data:/var/www/html/:rw
            - ./data:/var/www/html/data/:rw
            - ./var:/var/www/html/var/:rw
        networks:
            - backend
        user: "${PHP_UID:-0}:${PHP_GID:-0}"

    nginx:
        image: ghcr.io/rbrauner/learning-symfony-guestbook-nginx:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - ${NGINX_PORT_HTTP:-80}:80
            - ${NGINX_PORT_HTTPS:-443}:443
        depends_on:
            - php
        volumes_from:
            - php
        networks:
            - backend
        user: "${NGINX_UID:-0}:${NGINX_GID:-0}"

    database:
        image: ghcr.io/rbrauner/learning-symfony-guestbook-database:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        environment:
            - POSTGRES_DB=${POSTGRES_DB:-app}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
            - POSTGRES_USER=${POSTGRES_USER:-app}
        ports:
            - ${POSTGRES_PORT:-5432}:5432
        volumes:
            - ./var/database-data:/var/lib/postgresql/data:rw
        networks:
            - backend
        user: "${DATABASE_UID:-0}:${DATABASE_GID:-0}"

    mailer:
        image: ghcr.io/rbrauner/learning-symfony-guestbook-mailer:${TAG:-latest}
        platform: linux/x86_64
        working_dir: /var/www/html
        ports:
            - 1025
            - 1080
        networks:
            - backend
        user: "${MAILER_UID:-0}:${MAILER_GID:-0}"

volumes:
    app_data:

networks:
    backend:
