name: Publish in GitHub Package Registry

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set env
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            # - name: Test
            #   run: |
            #     echo $RELEASE_VERSION
            #     echo ${{ env.RELEASE_VERSION }}
            - name: Docker compose build latest
              run: DOCKER_IMAGE_TAG=latest docker compose -f ./docker-compose.build.yml build
            - name: Docker compose build tag
              run: DOCKER_IMAGE_TAG=$RELEASE_VERSION docker compose -f ./docker-compose.build.yml build
            - name: Docker compose push latest
              run: DOCKER_IMAGE_TAG=latest docker compose -f ./docker-compose.build.yml push
            - name: Docker compose push tag
              run: DOCKER_IMAGE_TAG=$RELEASE_VERSION docker compose -f ./docker-compose.build.yml push
